code/web/app/blueprints/users/routes.py
import hashlib, os
from werkzeug import secure_filename
from flask import (
    Blueprint,
    render_template,
    g,
    redirect,
    url_for,
    request,
    flash,
    current_app,
    send_file
)
from app.decorators import (
    is_logged_in,
    is_personal,
    is_teacher
)
from app.blueprints.users import controller
from app.blueprints.users.models import (
    User,
    GeneralInfo,
    HighschoolInfo,
    PopulationInfo,
    Log
)
from app.blueprints.users.forms import (
    UserForm,
    GeneralInfoForm,
    HighschoolInfoForm,
    PopulationInfoForm,
    UniversityInfoForm
)
from run import db

users = Blueprint('users', __name__, template_folder='templates', url_prefix='/users')

PER_PAGE = 3

@users.route('/', methods=["GET"])
@is_logged_in
def home():
    page = request.args.get('page', 1, type=int)
    all_users = User.query.paginate(page=page, per_page=PER_PAGE)
    return render_template("users.html", users=all_users, context=g.user_context)

@users.route('/<int:user_id>', methods=["GET"])
@is_logged_in
def show_user(user_id):
    user = User.query.filter_by(id=user_id).first_or_404()
    return render_template("user/show.html", context=g.user_context, user=user)

@users.route('/<int:user_id>/photo/edit', methods = ['GET', 'POST'])
@is_logged_in
def update_photo(user_id):
    user = User.query.filter_by(id=user_id).first_or_404()
    if request.method == 'POST':
        f = request.files['file']
        current_app.logger.info(f.filename)
        secure_name = secure_filename(f.filename)
        extension = secure_name[-4:]
        hash_value = hashlib.md5(secure_name.encode()).hexdigest()
        # Burda static dizine versek cok iyi olur.
        file_path = "/tmp/{}{}".format(hash_value, extension)
        current_app.logger.info(file_path)
        f.save(file_path)
        user.photoname = "{}{}".format(hash_value, extension)
        db.session.commit()
        flash('file uploaded successfully, refresh page')
        return redirect(url_for('users.show_user', user_id=user_id))

    return render_template('user/upload_photo.html', context=g.user_context)

@users.route('/<int:user_id>/photo')
@is_logged_in
def return_file(user_id):
    user = User.query.filter_by(id=user_id).first_or_404()
    try:
        return send_file("/tmp/{}".format(user.photoname), attachment_filename=user.photoname)
    except Exception as e:
        return str(e)

@users.route('/<int:user_id>/university_info', methods=["GET"])
@is_logged_in
def show_user_university_info(user_id):
    user = User.query.filter_by(id=user_id).first_or_404()
    return render_template("user/university_info/show.html", context=g.user_context, user=user)

@users.route('/<int:user_id>/university_info/edit', methods = ['GET', 'POST'])
@is_logged_in
def edit_user_university_info(user_id):
    user = User.query.filter_by(id=user_id).first_or_404()
    form = UniversityInfoForm(request.form)
    if request.method == 'POST' and form.validate():
        # Update Edilmeli ve Log yazilmali.
        current_app.logger.info("validated")
        controller.update_university_info(
            university_info=user.university_info[0],
            university_student_no=form.university_student_no.data,
            faculty=form.faculty.data,
            department=form.department.data,
            teaching_style=form.teaching_style.data,
            student_score=form.student_score.data,
            completed_yok=form.completed_yok.data
        )
        flash('Universite Bilgileri guncellendi.')
        return redirect(url_for('users.show_user_university_info', user_id=user_id))

    form.university_student_no.data = str(user.university_info[0].university_student_no)
    form.faculty.data = user.university_info[0].faculty
    form.department.data = user.university_info[0].department
    form.student_score.data = user.university_info[0].student_score
    form.teaching_style.data = user.university_info[0].teaching_style
    form.completed_yok.data = user.university_info[0].completed_yok
    return render_template('user/university_info/edit.html', context=g.user_context, form=form, user=user)


@users.route('/<int:user_id>/population_info', methods=["GET"])
@is_logged_in
def show_user_population_info(user_id):
    user = User.query.filter_by(id=user_id).first()
    return render_template("user/population_info/show.html", context=g.user_context, user=user)

@users.route('/<int:user_id>/population_info/edit', methods = ['GET', 'POST'])
@is_logged_in
def edit_user_population_info(user_id):
    user = User.query.filter_by(id=user_id).first_or_404()
    form = PopulationInfoForm(request.form)
    if request.method == 'POST' and form.validate():
        controller.update_population_info(
            population_info=user.population_info[0],
            neighborhoodNvillage=form.neighborhoodNvillage.data,
            population_administration=form.population_administration.data,
            c_no=form.c_no.data,
            id_card_no=form.id_card_no.data,
            family_queue_no=form.family_queue_no.data,
            queue_no=form.queue_no.data
        )
        flash('Nufus Bilgileri guncellendi.')
        return redirect(url_for('users.show_user_population_info', user_id=user_id))

    form.c_no.data = user.population_info[0].c_no
    form.family_queue_no.data = user.population_info[0].family_queue_no
    form.id_card_no.data = user.population_info[0].id_card_no
    form.neighborhoodNvillage.data = user.population_info[0].neighborhoodNvillage
    form.population_administration.data = user.population_info[0].population_administration
    form.queue_no.data = user.population_info[0].queue_no
    return render_template('user/population_info/edit.html', context=g.user_context, form=form, user=user)

@users.route('/<int:user_id>/highschool_info', methods=["GET"])
@is_logged_in
def show_user_highschool_info(user_id):
    user = User.query.filter_by(id=user_id).first_or_404()
    return render_template("user/highschool_info/show.html", context=g.user_context, user=user)

@users.route('/<int:user_id>/highschool_info/edit', methods = ['GET', 'POST'])
@is_logged_in
def edit_user_highschool_info(user_id):
    user = User.query.filter_by(id=user_id).first_or_404()
    form = HighschoolInfoForm(request.form)
    if request.method == 'POST' and form.validate():
        current_app.logger.info("form validated!")
        controller.update_highschool_info(
            highschool_info=user.highschool_info[0],
            school_name=form.school_name.data,
            school_department=form.school_department.data,
            diploma_success_note=form.diploma_success_note.data,
            diploma_course_branch=form.diploma_course_branch.data,
            foreign_language=form.foreign_language.data
        )
        flash('Lise Bilgileri guncellendi.')
        return redirect(url_for('users.show_user_highschool_info', user_id=user_id))

    form.diploma_course_branch.data = user.highschool_info[0].diploma_course_branch
    form.diploma_success_note.data = user.highschool_info[0].diploma_success_note
    form.school_name.data = user.highschool_info[0].school_name
    form.school_department.data = user.highschool_info[0].school_department
    form.foreign_language.data = user.highschool_info[0].foreign_language
    return render_template('user/highschool_info/edit.html', context=g.user_context, form=form, user=user)

@users.route('/<int:user_id>/general_info', methods=["GET"])
@is_logged_in
def show_user_general_info(user_id):
    user = User.query.filter_by(id=user_id).first()
    return render_template("user/general_info/show.html", context=g.user_context, user=user)

@users.route('/<int:user_id>/general_info/edit', methods = ['GET', 'POST'])
@is_logged_in
def edit_user_general_info(user_id):
    user = User.query.filter_by(id=user_id).first_or_404()
    form = GeneralInfoForm(request.form)
    if request.method == 'POST' and form.validate():
        current_app.logger.info("form validated!")
        controller.update_general_info(
            general_info=user.general_info[0],
            tc=form.tc.data,
            nationality=form.nationality.data,
            gender=form.gender.data,
            birthplace=form.birthplace.data,
            birthdate=form.birthdate.data,
            pension_fund=form.pension_fund.data,
            military_service=form.military_service.data,
            disability_status=form.disability_status.data,
            preference_order=form.preference_order.data,
            is_want_scholarship=form.is_want_scholarship.data
        )
        flash('Kişisel Bilgileri guncellendi.')
        return redirect(url_for('users.show_user_general_info', user_id=user_id))

    form.tc.data = user.general_info[0].tc
    form.nationality.data = user.general_info[0].nationality
    form.gender.data = user.general_info[0].gender
    form.birthplace.data = user.general_info[0].birthplace
    form.birthdate.data = user.general_info[0].birthdate
    form.pension_fund.data = user.general_info[0].pension_fund
    form.disability_status.data = user.general_info[0].disability_status
    form.is_want_scholarship.data = user.general_info[0].is_want_scholarship
    form.military_service.data = user.general_info[0].military_service
    form.preference_order.data = user.general_info[0].preference_order
    return render_template('user/general_info/edit.html', context=g.user_context, form=form, user=user)

@users.route('/<int:user_id>/login_info/log/<string:field>/<int:object_id>', methods=["GET"])
@is_logged_in
def show_user_login_info_in_log(user_id, field, object_id):
    logs = Log.query.filter_by(model='User').filter_by(field=field).filter_by(object_id=object_id).all()
    return render_template("logs.html", context=g.user_context, logs=logs)

@users.route('/<int:user_id>/login_info', methods=["GET"])
@is_logged_in
def show_user_login_info(user_id):
    user = User.query.filter_by(id=user_id).first_or_404()

code/web/app/templates/includes/_menu.html
<div class="leftContainer">
    <div class="mainStatus">
        <div class="usernameAndStatus">
            <div class="uName">{{ context.user.first_name }} {{context.user.middle_name }} {{context.user.surname}}<span>({{ context.user.role.name }})</span></div>
        </div>
        <div class="dateIp">
            <div class="loginDate">Login Date: {{ context.login_date }}</div>
            <div class="loginIp">Login Ip: {{ context.ip }}</div>
        </div>
    </div>
    <div class="menuContainer">
        <div class="menuTitle">Islemler</div>
        <ul class="menu-list">
            <li drop><a href="{{ url_for('users.show_user', user_id=context.user.id)}}">Profilim</a>
                <ul class="drop-down animation">
                        <li> <a href="{{ url_for('users.show_user_login_info', user_id=context.user.id) }}">Giriş Bilgilerim</a> </li>
                        <li>
                            <a href="{{ url_for('users.show_user_general_info', user_id=context.user.id) }}">Kişisel Bilgilerim</a>
                        </li>
                        <li>
                            <a href="{{ url_for('users.show_user_highschool_info', user_id=context.user.id) }}">Lise Bilgilerim</a>
                        </li>
                        <li>
                            <a href="{{ url_for('users.show_user_population_info', user_id=context.user.id) }}">Nufus Bilgilerim</a>
                        </li>
                        <li>
                            <a href="{{ url_for('users.show_user_university_info', user_id=context.user.id) }}">Universite Bilgilerim</a>
                        </li>
                </ul>
            </li>
            {% if context.user.role_id != 3 %}
            <li drop><a href="#">Danışmanlık Sistemi</a>
              <ul class="drop-down animation">
                <li><a href="{{ url_for('show_consultancy', user_id=context.user.id) }}">Danışmanı olduğum kişiler</a></li>
                {% if context.user.role.access('AssignCons') %}
                    <li><a href="{{ url_for('assign_consultant') }}">Danışmanı ata</a></li>
                    <li><a href="{{ url_for('show_all_consultancy') }}">Tüm Danışmanlık İlişkileri</a></li>
                {% endif %}
              </ul>
            </li>
            {% endif %}
            {% if context.user.role.access('CreateUser') %}
                <li drop><a href="#">Kullanıcı ekle</a>
                    <ul class="drop-down animation">
                        <li> <a href="{{ url_for('users.create') }}">Yeni Kullanici Olustur</a> </li>
                        <li> <a href="{{ url_for('users.auto_create_users') }}">Dosyadan Yükle</a> </li>
                    </ul>
                </li>
            {% endif %}
            {% if context.user.role.access('SeeAllUser') %}
                <li><a href="{{ url_for('users.home') }}">Tüm Kullanicilar</a></li>
            {% endif %}
        </ul>
        <div class="logoutContainer">
            <button type="button" onclick="location.href='/logout';">Logout</button>
        </div>
    </div>

</div>

code/web/app/templates/includes/_messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
  {% for category, message in messages %}
    <div class="alert alert-{{category}}">{{message}}</div>
  {% endfor %}
{% endif %}
{% endwith %}

{% if error %}
    <div class="alert alert-danger">{{error}}</div>
{% endif %}

{% if msg %}
    <div class="alert alert-success">{{error}}</div>
{% endif %}

code/web/app/templates/includes/_navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <a class="navbar-brand" href="#">BiUsis</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="/about">About Us</a>
      </li>
      {% if session.logged_in %}
        <li class="nav-item">
          <a class="nav-link" href="/logout">Logout</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="/register">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/login">Login</a>
        </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>